// Generated by CoffeeScript 1.9.3
var camera, config, engine, scene;

config = Config.get();

config.fillWindow();

config.transparentBackground = true;

config.raiseDelay = 5000;

camera = new THREE.PerspectiveCamera(30, config.width / config.height, 1, 10000);

camera.position.set(0, -120, 6100);

engine = new Engine3D();

engine.setCamera(camera);

scene = new TkwIntro();

engine.addScene(scene);

engine.render();
