// Generated by CoffeeScript 1.9.3
var TkwIntro,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

TkwIntro = (function(superClass) {
  extend(TkwIntro, superClass);

  function TkwIntro() {
    TkwIntro.__super__.constructor.call(this);
    this.cloud = new Cloud({
      cloudSize: config.cloudSize / 2
    });
    this.scene.add(this.cloud.mesh);
    this.cloud2 = new Cloud({
      cloudSize: config.cloudSize / 2
    });
    this.cloud2.mesh.position.z -= config.cloudSize / 2;
    this.scene.add(this.cloud2.mesh);
    this.text = new Paper({
      key: 'text',
      x: 0,
      y: 10,
      z: config.cloudSize / 2 - 450,
      sX: 73.7,
      sY: 10.2
    });
    this.scene.add(this.text.mesh);
    this.plane = new Paper({
      key: 'plane',
      x: Paper.FAR_AWAY,
      y: Paper.FAR_AWAY,
      z: config.cloudSize / 2 - 450,
      tX: 41,
      tY: 15,
      sX: 22.3,
      sY: 14.7
    });
    this.scene.add(this.plane.mesh);
    this.loaded = true;
    SoundManager.get().play('intro');
    setTimeout((function(_this) {
      return function() {
        var tween;
        return tween = new TWEEN.Tween({
          y: camera.position.y
        }).to({
          y: 20
        }, config.raiseDuration).easing(TWEEN.Easing.Exponential.Out).onUpdate(function() {
          return camera.position.y = this.y;
        }).start();
      };
    })(this), config.raiseDelay);
    setTimeout((function(_this) {
      return function() {
        var tween;
        return tween = new TWEEN.Tween(_this.plane.farAwayPosition()).to(_this.plane.targetPosition(), config.raiseDuration + 1000).easing(TWEEN.Easing.Elastic.Out).onUpdate(function() {
          scene.plane.mesh.position.x = this.x;
          return scene.plane.mesh.position.y = this.y;
        }).start();
      };
    })(this), config.raiseDelay);
  }

  TkwIntro.prototype.tick = function(tpf) {
    var budge;
    if (!this.loaded) {
      return;
    }
    SoundManager.get().updateGlobalVolume(0.2);
    budge = config.flightSpeed * tpf;
    camera.position.z -= budge;
    this.text.mesh.position.z -= budge;
    this.plane.mesh.position.z -= budge;
    if (camera.position.z < this.cloud.mesh.position.z) {
      this.cloud.mesh.position.z -= config.cloudSize;
    }
    if (camera.position.z < this.cloud2.mesh.position.z) {
      return this.cloud2.mesh.position.z -= config.cloudSize;
    }
  };

  TkwIntro.prototype.doMouseEvent = function(event, raycaster) {};

  TkwIntro.prototype.doKeyboardEvent = function(event) {};

  return TkwIntro;

})(BaseScene);
