// Generated by CoffeeScript 1.10.0
var app;

app = angular.module('app', ['ui.bootstrap', 'ngAnimate', 'ngRoute']);

app.config([
  '$routeProvider', function($routeProvider) {
    $routeProvider.when('/home', {
      templateUrl: 'partials/home.html',
      controller: 'HomeCtrl'
    }).when('/about', {
      templateUrl: 'partials/about.html',
      controller: 'AboutCtrl'
    }).otherwise({
      redirectTo: '/home'
    });
  }
]);

app.controller('HomeCtrl', function($scope) {});

app.controller('AboutCtrl', function($scope) {});

app.controller('CarouselCtrl', function($scope) {
  $scope.options = {
    interval: 5000,
    noWrapSlides: false,
    slides: [
      {
        image: 'images/img_carousel1.png',
        text: 'asd'
      }, {
        image: 'images/img_carousel2.png',
        text: 'asd'
      }, {
        image: 'images/img_carousel3.png',
        text: 'asd'
      }, {
        image: 'images/img_carousel4.png',
        text: 'asd'
      }, {
        image: 'images/img_carousel5.png',
        text: 'asd'
      }, {
        image: 'images/img_carousel6.png',
        text: 'asd'
      }
    ]
  };
});
